FROM debian:buster-20170723

RUN apt-get update && apt-get install -y \
        tmux \
        git \
        locales \
        curl

RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen && locale-gen

RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

